<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengadaan_model extends CI_Model
{

    public $table = 'pengadaan';
    public $id = 'pengadaan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('pengadaan_id,pengadaan_tanggal,buku_id,pengadaan_asal_buku,pengadaan_jumlah,pengadaan_keterangan');
        $this->datatables->from('pengadaan');
        //add this line for join
        //$this->datatables->join('table2', 'pengadaan.field = table2.field');
        $this->datatables->add_column('action', '
        	<button type="button" class="btn btn-info btn-sm" onclick="btnEdit(\'$1\')" title="Edit"> <i class="fa fa-pencil" aria-hidden="true"></i> </button>
        	<button type="button" class="btn btn-danger btn-sm" onclick="btnDel(\'$1\')" title="Hapus"> <i class="fa fa-trash" aria-hidden="true"></i> </button>
        	', 'pengadaan_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('pengadaan_id', $q);
        $this->db->or_like('pengadaan_tanggal', $q);
        $this->db->or_like('buku_id', $q);
        $this->db->or_like('pengadaan_asal_buku', $q);
        $this->db->or_like('pengadaan_jumlah', $q);
        $this->db->or_like('pengadaan_keterangan', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('deleted_by', $q);
        $this->db->or_like('deleted_date', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pengadaan_id', $q);
        $this->db->or_like('pengadaan_tanggal', $q);
        $this->db->or_like('buku_id', $q);
        $this->db->or_like('pengadaan_asal_buku', $q);
        $this->db->or_like('pengadaan_jumlah', $q);
        $this->db->or_like('pengadaan_keterangan', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('deleted_by', $q);
        $this->db->or_like('deleted_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Pengadaan_model.php */
/* Location: ./application/models/Pengadaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-20 15:04:50 */
/* http://harviacode.com */