<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pinjam_model extends CI_Model
{

    public $table = 'pinjam';
    public $id = 'pinjam_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('siswa.siswa_nama as siswa_nama, pinjamitem.buku_id as buku_id, buku.buku_judul as buku_judul, pinjam.*');
        $this->datatables->from('pinjam');
        //add this line for join
        //$this->datatables->join('table2', 'pinjam.field = table2.field');
        $this->datatables->join('siswa', 'pinjam.siswa_id = siswa.siswa_id');
        $this->datatables->join('pinjamitem', 'pinjam.pinjam_id = pinjamitem.pinjam_id');
        $this->datatables->join('buku', 'pinjamitem.buku_id = buku.buku_id');
        $this->datatables->group_by("pinjam.pinjam_id");

        $this->datatables->add_column('action', anchor(site_url('pinjam/read/$1'), 'Read') . " | " . anchor(site_url('pinjam/update/$1'), 'Update') . " | " . anchor(site_url('pinjam/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'pinjam_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('pinjam_id', $q);
        $this->db->or_like('kodeunik_pinjam', $q);
        $this->db->or_like('pinjam_tanggal', $q);
        $this->db->or_like('siswa_id', $q);
        $this->db->or_like('pinjam_ket', $q);
        $this->db->or_like('pinjam_lama', $q);
        $this->db->or_like('pinjam_status', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('deleted_by', $q);
        $this->db->or_like('deleted_date', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pinjam_id', $q);
        $this->db->or_like('kodeunik_pinjam', $q);
        $this->db->or_like('pinjam_tanggal', $q);
        $this->db->or_like('siswa_id', $q);
        $this->db->or_like('pinjam_ket', $q);
        $this->db->or_like('pinjam_lama', $q);
        $this->db->or_like('pinjam_status', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('deleted_by', $q);
        $this->db->or_like('deleted_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function get_kodePinjam()
    {
        $sql = "SELECT MAX(RIGHT(kodeunik_pinjam,4)) AS kd_max FROM pinjam WHERE MID(kodeunik_pinjam,3,6)=DATE_FORMAT(CURDATE(),'%y%m%d')";
        $q = $this->db->query($sql);
        $kd = "";
        if ($q->num_rows() > 0) {
            foreach ($q->result() as $k) {
                $tmp = ((int)$k->kd_max) + 1;
                $kd = sprintf("%04s", $tmp);
            }
        } else {
            $kd = "0001";
        }
        $kode = "PB" . date('ymd') . $kd;
        return $kode;
    }
}

/* End of file Pinjam_model.php */
/* Location: ./application/models/Pinjam_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-20 15:04:50 */
/* http://harviacode.com */