<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siswa_model extends CI_Model
{

    public $table = 'siswa';
    public $id = 'siswa_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('siswa_id,siswa_nama,siswa_nisn,siswa_kelamin,siswa_agama,siswa_tempat_lhr,siswa_tanggal_lhr,siswa_alamat,siswa_no_hp,siswa_foto');
        $this->datatables->from('siswa');
        //add this line for join
        //$this->datatables->join('table2', 'siswa.field = table2.field');
        $this->datatables->add_column(
            'action',
            '
        	<button type="button" class="btn btn-info btn-sm" onclick="btnEdit(\'$1\')" title="Edit"> <i class="fa fa-pencil" aria-hidden="true"></i> </button>
        	<button type="button" class="btn btn-danger btn-sm" onclick="btnDel(\'$1\')" title="Hapus"> <i class="fa fa-trash" aria-hidden="true"></i> </button>',
            'siswa_id'
        );
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('siswa_id', $q);
        $this->db->or_like('siswa_nama', $q);
        $this->db->or_like('siswa_nisn', $q);
        $this->db->or_like('siswa_kelamin', $q);
        $this->db->or_like('siswa_agama', $q);
        $this->db->or_like('siswa_tempat_lhr', $q);
        $this->db->or_like('siswa_tanggal_lhr', $q);
        $this->db->or_like('siswa_alamat', $q);
        $this->db->or_like('siswa_no_hp', $q);
        $this->db->or_like('siswa_foto', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('deleted_by', $q);
        $this->db->or_like('deleted_date', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('siswa_id', $q);
        $this->db->or_like('siswa_nama', $q);
        $this->db->or_like('siswa_nisn', $q);
        $this->db->or_like('siswa_kelamin', $q);
        $this->db->or_like('siswa_agama', $q);
        $this->db->or_like('siswa_tempat_lhr', $q);
        $this->db->or_like('siswa_tanggal_lhr', $q);
        $this->db->or_like('siswa_alamat', $q);
        $this->db->or_like('siswa_no_hp', $q);
        $this->db->or_like('siswa_foto', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('deleted_by', $q);
        $this->db->or_like('deleted_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Siswa_model.php */
/* Location: ./application/models/Siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-20 15:04:50 */
/* http://harviacode.com */