<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pinjam_model extends CI_Model
{

    public $table = 'pinjam';
    public $id = 'pinjam_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('pinjam_id,kodeunik_pinjam,pinjam_tanggal,siswa_id,pinjam_ket,pinjam_lama,pinjam_status,created_by,created_date,updated_by,updated_date,deleted_by,deleted_date');
        $this->datatables->from('pinjam');
        //add this line for join
        //$this->datatables->join('table2', 'pinjam.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pinjam/read/$1'),'Read')." | ".anchor(site_url('pinjam/update/$1'),'Update')." | ".anchor(site_url('pinjam/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'pinjam_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('pinjam_id', $q);
	$this->db->or_like('kodeunik_pinjam', $q);
	$this->db->or_like('pinjam_tanggal', $q);
	$this->db->or_like('siswa_id', $q);
	$this->db->or_like('pinjam_ket', $q);
	$this->db->or_like('pinjam_lama', $q);
	$this->db->or_like('pinjam_status', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('deleted_by', $q);
	$this->db->or_like('deleted_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pinjam_id', $q);
	$this->db->or_like('kodeunik_pinjam', $q);
	$this->db->or_like('pinjam_tanggal', $q);
	$this->db->or_like('siswa_id', $q);
	$this->db->or_like('pinjam_ket', $q);
	$this->db->or_like('pinjam_lama', $q);
	$this->db->or_like('pinjam_status', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('deleted_by', $q);
	$this->db->or_like('deleted_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pinjam_model.php */
/* Location: ./application/models/Pinjam_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-20 15:04:50 */
/* http://harviacode.com */